name: RunChecks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install argparse pylint
    - name: Analysing the code with pylint
      run: |
        pylint -dR0913,R0914,R0912,R0801 sbomtools/*.py
    - name: Attempting install
      run: |
        pip install .
